services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    volumes:
      - ./db-data/transactions.csv:/root/transactions.csv 
      - db-data:/root/db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - db-data:/root/db

volumes:
  db-data:
